version: "3.9"

services:
  fcgi_server:
    build: fcgi_server
    container_name: fcgicontainer
    ports:
      - "81:81"

  nginx_server:
    image: nginx
    container_name: nginxcontainer
    ports:
      - "80:8080"
    volumes:
      - "./nginx_server/nginx/nginx.conf:/etc/nginx/nginx.conf"